#config_version=6

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 150

sound_player:
  song_song1_selected:
    song1:
      bus: music
      action: play
      loops: -1
  song_song2_selected:
    song2:
      bus: music
      action: play
      loops: -1
  song_song3_selected:
    song3:
      bus: music
      action: play
      loops: -1
