#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_song
    - start_mode_bumpers
  mode_base_will_stop:
    - stop_mode_song
    - stop_mode_bumpers

slide_player:
  mode_base_started: base

sound_player:
  mode_base_started:
    c-love:
      bus: music
