#config_version=6

mode:
  start_events: song_song1_selected
  stop_events: ball_will_end
  priority: 150

light_player:
  mode_song1_started:
    gi:
      color: ff2200
      fade: 300ms

sound_player:
  mode_song1_started:
    song1:
      bus: music
      action: play
  mode_song1_will_stop:
    song1:
      bus: music
      action: stop
