#config_version=6

mode:
  start_events: song_song2_selected
  stop_events: ball_will_end
  priority: 150

light_player:
  mode_song2_started:
    gi:
      color: 0055ff
      fade: 300ms

sound_player:
  mode_song2_started:
    song2:
      bus: music
      action: play
  mode_song2_will_stop:
    song2:
      bus: music
      action: stop
