#config_version=6

mode:
  start_events: start_song_selection_mode, show_song_selection_mode
  stop_events: song_selection_item_selected
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 120

mode_settings:
  selectable_items: song1, song2, song3
  select_item_events: s_start_active
  next_item_events: s_flipper_right_active
  previous_item_events: s_flipper_left_active
# TODO: add some slides. If you have a nice example please send it to us (or create a PR).
variable_player:
  song_selection_song1_highlighted:
    hightlighted_song:
      string: "Sonic"
      action: set
  song_selection_song2_highlighted:
    hightlighted_song:
      string: "Mario"
      action: set
  song_selection_song3_highlighted:
    hightlighted_song:
      string: "Luigi"
      action: set

  song_selection_song1_selected:
    selected_song:
      string: "Sonic"
      action: set
  song_selection_song2_selected:
    selected_song:
      string: "Mario"
      action: set
  song_selection_song3_selected:
    selected_song:
      string: "Luigi"
      action: set
