#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

machine:
  balls_installed: 3
  min_balls: 3

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml

modes:
  - attract
  - base
  - bumpers
  - song
  - song1
  - song2
  - song3

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default

# flippers:
#     left_flipper:
#         main_coil: c_flipper_left_main
#         hold_coil: c_flipper_left_hold
#         activation_switch: s_left_flipper
#         enable_events: machine_reset_phase_3
        
#     right_flipper:
#         main_coil: c_flipper_right_main
#         hold_coil: c_flipper_right_hold
#         activation_switch: s_right_flipper
#         enable_events: machine_reset_phase_3

# coils:
#     c_flipper_left_main:
#         number: 0-0
#         default_pulse_ms: 25
#     c_flipper_left_hold:
#         number: 0-1
#         allow_enable: true
        
#     c_flipper_right_main:
#         number: 0-2
#         default_pulse_ms: 20
#     c_flipper_right_hold:
#         number: 0-3
#         allow_enable: true

# switches:
#     s_left_flipper:
#         number: 0-0
#         tags: left_flipper
#     s_right_flipper:
#         number: 0-1
#         tags: right_flipper

virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3
