#config_version=6

config:
  - config_switches.yaml
  - config_coils.yaml
  - config_ball_devices.yaml

machine:
  balls_installed: 3
  min_balls: 3

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default

modes:
  - attract
  - base
  - bumpers
  - song
  - song1
  - song2
  - song3
  - tilt

virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3

lights:
  led_1:
    number: 0-0-0
    subtype: led
    type: grb
  led_2:
    number: 0-0-1
    subtype: led
    type: grb
  led_3:
    number: 0-0-2
    subtype: led
    type: grb
  led_4:
    number: 0-0-3
    subtype: led
    type: grb
  led_5:
    number: 0-0-4
    subtype: led
    type: grb

light_player:
  test_on:
    led_1: darkred       # 0-0-0
    led_2: blue          # 0-0-1
    led_3: darkgray      # 0-0-2
    led_4: darkgreen     # 0-0-3
    led_5: white         # 0-0-4
  test_off:
    led_1: off
    led_2: off
    led_3: off
    led_4: off
    led_5: off