#config_version=6

config:
  - config_switches.yaml
  - config_coils.yaml
  - config_ball_devices.yaml

machine:
  balls_installed: 3
  min_balls: 3

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default

modes:
  - attract
  - base
  - bumpers
  - song
  - song1
  - song2
  - song3
  - tilt

virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3