#config_version=6

lights:
  led_1:
    number: 0-0-0
    subtype: led
    type: grb
  led_2:
    number: 0-0-1
    subtype: led
    type: grb
  led_3:
    number: 0-0-2
    subtype: led
    type: grb
  led_4:
    number: 0-0-3
    subtype: led
    type: grb
light_player:
  test_on:
    led_1: darkred       # 0-0-0
    led_2: blue          # 0-0-1
    led_3: darkgray      # 0-0-2
    led_4: darkgreen     # 0-0-3
  test_off:
    led_1: off
    led_2: off
    led_3: off
    led_4: off
