#config_version=6

lights:
  led_1:
    channels:
      green:
        number: 0-0-0
      red:
        number: 0-0-1
      blue:
        number: 0-0-2
  led_2:
    channels:
      green:
        number: 0-0-4
      red:
        number: 0-0-5
      blue:
        number: 0-0-6
  led_3:
    channels:
      green:
        number: 0-0-8
      red:
        number: 0-0-9
      blue:
        number: 0-0-10
  led_4:
    channels:
      green:
        number: 0-0-12
      red:
        number: 0-0-13
      blue:
        number: 0-0-14
  led_5:
    channels:
      green:
        number: 0-0-16
      red:
        number: 0-0-17
      blue:
        number: 0-0-18
light_player:
  test_on:
    led_1: darkred
    led_2: blue
    led_3: darkgray
    led_4: darkgreen
    led_5: purple
  test_off:
    led_1: off
    led_2: off
    led_3: off
    led_4: off
    led_5: off
