#config_version=6

config:
  - config_lights.yaml
  - config_switches.yaml
  - config_coils.yaml
  - config_ball_devices.yaml
  - config_game.yaml

machine:
  balls_installed: 1
  min_balls: 1

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default

modes:
  - attract
  - base
  - bonus
  - bumpers
  - song
  - song1
  - song2
  - song3
  - tilt

random_event_player:
  song_hard_rock_selected:
    events:
      - song_song1_selected
      - song_song2_selected
  song_metal_selected:
    events:
      - song_song3_selected

event_player:
  song_song1_selected:
    - start_mode_song1
  song_song2_selected:
    - start_mode_song2
  song_song3_selected:
    - start_mode_song3

virtual_platform_start_active_switches:
  - s_trough_1
#  - s_trough_2
#  - s_trough_3
