#config_version=6

switches:
  # Playfield Switches
  s_tilt_bob:
    number:
    tags: tilt_warning
  s_bumper_left:
    number:
  s_bumper_right:
    number:
  s_left_lane:
    number:
  # Cabinet Switches
  s_start:
    number:
    tags: start
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_right:
    number:
    tags: right_flipper
  # Trough Switches
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
    number: