#config_version=6

tilt:
  tilt_warning_switch_tag: tilt_warning
  tilt_switch_tag: tilt
  slam_tilt_switch_tag: slam_tilt
  warnings_to_tilt: 3
  reset_warnings_events: ball_ended
  multiple_hit_window: 500ms
  settle_time: 5s
  tilt_warnings_player_var: tilt_warnings
