#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode:
  start_events: start_mode_song
  stop_events: song_item_selected
  game_mode: true
  priority: 120
  code: mpf.modes.carousel.code.carousel.Carousel

mode_settings:
  selectable_items:
    - song1
    - song2
    - song3
  select_item_events: s_start_active
  previous_item_events: s_flipper_left_inactive
  next_item_events: s_flipper_right_inactive

slide_player:
  mode_song_started: song

event_player:
  song_song1_selected:
    - start_mode_song1
  song_song2_selected:
    - start_mode_song2
  song_song3_selected:
    - start_mode_song3

variable_player:
  song_song1_selected:
    selected_song:
      string: "Mario"
      action: set
  song_song2_selected:
    selected_song:
      string: "Sonic"
      action: set
  song_song3_selected:
    selected_song:
      string: "Luigi"
      action: set
  item_highlighted:
    highlighted_song:
      string: "{item}"
      action: set
#   item_highlighted:
#     slick-rick-lick:
#       bus: item_highlighted.item

# timers:
#   song_carousel_timer:
#     end_value: 1
#     tick_interval: 5s
#     start_running: true
#     control_events:
#       - event: item_highlighted
#         action: restart
#       - event: flipper_cradle
#         action: stop
#       - event: flipper_cradle_release
#         action: restart
